<?php echo $this->partial('partials/menu.phtml', array('nome' => 'Matheus')); ?>
<div class="page-header">
    <h1><?php echo $this->translate('Posts') ?> <small><?php echo $this->translate('Administração de Posts') ?></small></h1>
</div>
<div class="row">
    <div class="col-md-12">
        <p>
            <a class="btn btn-lg btn-default" href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'save')) ?>" target="_self">Novo</a>
        </p>
    </div>
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-hover">
            <tr>
                <th>Título</th>
                <th>Texto</th>
                <th>Data de Cadastro</th>
                <th style="width: 161px">Opções</th>
            </tr>
            <?php foreach ($posts as $post): ?>
                <tr>
                    <td><a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'post', 'id' => $post['id'])) ?>"><?php echo $this->escapeHtml($post['title']); ?></a></td>
                    <td><?php echo $this->escapeHtml($post['description']); ?></td>
                    <td><kbd><?php
                            echo $this->dateFormat(
                                    new DateTime($post['post_date']), IntlDateFormatter::MEDIUM, // date
                                    IntlDateFormatter::SHORT, // time
                                    "pt_BR"
                            );
                            ?></kbd></td>
                    <td style="width: 161px">
                        <div class="btn-group">
                            <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'save', 'id' => $post['id'])) ?>" title="Editar" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-edit"></span> Editar</a>
                            <a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'delete', 'id' => $post['id'])) ?>" rel="confirmation" title="Deseja excluir este registro?" class="btn btn-default btn-sm"> <span class="glyphicon glyphicon-trash"></span> Excluir</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php echo $this->paginationControl($posts, 'Sliding', 'partials/paginator/control_v2', array('route' => 'application/paginator')); ?>
    </div>
</div>